<?php

namespace Database\Seeders;

use App\Models\BodyStructure;
use App\Models\Equipment;
use App\Models\Exercise;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'canonical_name' => 'Farmer\'s Walk',
                'movement_pattern' => 'Carry',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Carry',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Primary grip and carry exercise throughout all phases',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Traps', 'Core', 'Shoulders'],
            ],
            [
                'canonical_name' => 'Farmer\'s Hold',
                'movement_pattern' => 'Hold',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Hold',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => 'Farmer\'s Walk',
                'shoulder_safety_notes' => null,
                'notes' => 'Static hold version of farmer\'s walk',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Traps', 'Core'],
            ],
            [
                'canonical_name' => 'Suitcase Carries',
                'movement_pattern' => 'Carry',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Carry',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Single-side carry emphasizing anti-lateral flexion',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Obliques', 'Core', 'Traps'],
            ],
            [
                'canonical_name' => 'Suitcase Holds',
                'movement_pattern' => 'Hold',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Hold',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => 'Suitcase Carries',
                'shoulder_safety_notes' => null,
                'notes' => 'Static hold version of suitcase carry',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Obliques', 'Core'],
            ],
            [
                'canonical_name' => 'Body Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-BB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Inverted row using barbell in rack',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Forearms', 'Core'],
            ],
            [
                'canonical_name' => 'Machine Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-LF-MR',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Seated 2 Arm Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Chest-supported selectorized row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Neutral Grip Seated 2 Arm Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Machine Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Seated cable row with neutral grip attachment',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Chest Supported DB Row (Spider)',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Incline bench chest-supported dumbbell row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Rear Delts', 'Forearms'],
            ],
            [
                'canonical_name' => 'Single-Arm Neutral Grip Cable Pulldown',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Slight lean back eliminates anterior capsule awareness',
                'notes' => 'Primary lat exercise from Phase 3 onward',
                'primary_muscle' => 'Lats',
                'secondary_muscles' => ['Biceps', 'Forearms', 'Rear Delts'],
            ],
            [
                'canonical_name' => 'Kneeling Cable Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Seated 2 Arm Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Kneeling position at seated cable row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Core', 'Forearms'],
            ],
            [
                'canonical_name' => 'Half-Kneeling Single Arm Cable Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Half-kneeling unilateral cable row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Core', 'Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Half-Kneeling Single-Arm Cable Row, Low-to-High Finish',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Half-Kneeling Single Arm Cable Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Low-to-high finish variant',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Rear Delts', 'Core', 'Biceps'],
            ],
            [
                'canonical_name' => 'Single-Arm Cable Row (Split Stance)',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Half-Kneeling Single Arm Cable Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Split stance cable row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Core', 'Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Seat Cable Row (V / Narrow Neutral Grip)',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Seated 2 Arm Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'V-grip narrow neutral cable row',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Plate Loaded Seated Row',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-PLM',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Machine Row',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Plate-loaded seated row machine',
                'primary_muscle' => 'Back',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Face Pull',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Standard face pull with rope',
                'primary_muscle' => 'Rear Delts',
                'secondary_muscles' => ['Traps', 'Rhomboids', 'External Rotators'],
            ],
            [
                'canonical_name' => 'Face Pull (w External Rotation)',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Face Pull',
                'shoulder_safety_notes' => 'Monitor right shoulder during external rotation',
                'notes' => 'Face pull with added external rotation component',
                'primary_muscle' => 'Rear Delts',
                'secondary_muscles' => ['External Rotators', 'Traps', 'Rhomboids'],
            ],
            [
                'canonical_name' => 'Rear Delt Cable Fly',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Face Pull',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Standing cable rear delt fly',
                'primary_muscle' => 'Rear Delts',
                'secondary_muscles' => ['Rhomboids', 'Traps'],
            ],
            [
                'canonical_name' => 'Chest Supported Rear Delt Fly',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Rear Delt Cable Fly',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Incline bench chest-supported rear delt fly',
                'primary_muscle' => 'Rear Delts',
                'secondary_muscles' => ['Rhomboids', 'Traps'],
            ],
            [
                'canonical_name' => 'Seated Single Arm DB Curl - Anchored',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Seated single-arm curl with opposite hand anchored',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Anchored Single Arm Dumbbell Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Seated Single Arm DB Curl - Anchored',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Standing or seated anchored curl',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Standing One Arm Extended Cable Curls',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cable curl with arm extended behind body',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Standing One Arm Bicep Curl with Cable (Anchored)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing One Arm Extended Cable Curls',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cable curl with elbow anchored',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Incline Dumbell Curl (Supinated)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Incline bench supinated dumbbell curl',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms'],
            ],
            [
                'canonical_name' => 'Incline DB Hammer Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Incline Dumbell Curl (Supinated)',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Incline bench hammer grip curl',
                'primary_muscle' => 'Brachialis',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'DB Spider Curl (Hammer)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Spider curl on incline bench with hammer grip',
                'primary_muscle' => 'Brachialis',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Alternate Seated DB Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'alternating',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Alternating seated dumbbell curl with supination',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Single Arm Rope Curl (extended Arm Position)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing One Arm Extended Cable Curls',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Single arm cable curl with rope grip',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Brachialis', 'Forearms'],
            ],
            [
                'canonical_name' => 'Hammer Curls with Rope and Cable',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Rope attachment hammer curl on cable',
                'primary_muscle' => 'Brachialis',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Cross Body Cable Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cross-body cable curl',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Brachialis', 'Forearms'],
            ],
            [
                'canonical_name' => 'Standing Single Arm Cable Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing One Arm Extended Cable Curls',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Standard single arm cable curl',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms', 'Brachialis'],
            ],
            [
                'canonical_name' => 'Dumbbell Incline Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Incline Dumbell Curl (Supinated)',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Incline dumbbell curl variant',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms'],
            ],
            [
                'canonical_name' => '1 Arm Cable Curl',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Single arm cable curl',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Forearms'],
            ],
            [
                'canonical_name' => 'Dumbbell: Squeeze Curl - Neutral',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Dumbbell squeeze curl variations',
                'primary_muscle' => 'Biceps',
                'secondary_muscles' => ['Brachialis', 'Forearms'],
            ],
            [
                'canonical_name' => 'Dumbbell: Squeeze Curl - Hammer',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Hammer grip squeeze curl',
                'primary_muscle' => 'Brachialis',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'DB Cross Body Curl (Hammer Grip)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cross body hammer curl with dumbbell',
                'primary_muscle' => 'Brachialis',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
            [
                'canonical_name' => 'Neutral Grip Dumbbell Floor Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Right anterior capsule awareness during heavy sets; neutral grip well tolerated',
                'notes' => 'Primary pressing movement from Phase 6 onward',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'Smith Machine Bench Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-SM',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Dumbbell Floor Press',
                'shoulder_safety_notes' => 'Right anterior capsule tightness; monitor closely',
                'notes' => 'Used in Phases 3-4',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'Supine Press Machine - Plate Loaded (Planet Fitness)',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-PLM',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Dumbbell Floor Press',
                'shoulder_safety_notes' => 'Some right capsule tightness at higher weights',
                'notes' => 'Planet Fitness specific plate-loaded press',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'DB Neutral Press (slight Rotate To Underhand)',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Dumbbell Floor Press',
                'shoulder_safety_notes' => 'Neutral grip well tolerated',
                'notes' => 'Floor press or bench press with neutral grip and slight underhand rotation',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'Low-Incline DB Press (15-30°)',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Left trap compensation noted; monitor',
                'notes' => 'Low incline dumbbell press',
                'primary_muscle' => 'Upper Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'Single Arm Cable Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Right extension not as strong as left; some trap recruitment',
                'notes' => 'Single arm cable press in split stance',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts', 'Core'],
            ],
            [
                'canonical_name' => 'Single Arm Cable Press (split stance)',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single Arm Cable Press',
                'shoulder_safety_notes' => 'Right extension not as strong as left',
                'notes' => 'Split stance variant',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts', 'Core'],
            ],
            [
                'canonical_name' => 'Machine Chest Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-LF-CP',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Neutral Grip Dumbbell Floor Press',
                'shoulder_safety_notes' => 'Right anterior capsule awareness on eccentric',
                'notes' => 'Selectorized chest press machine',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts'],
            ],
            [
                'canonical_name' => 'Single-Arm Vertical Plate Balance Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-PLT',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Left has more control than right',
                'notes' => 'Vertical plate balance floor press',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Stabilizers', 'Core'],
            ],
            [
                'canonical_name' => 'Single-Arm DB Balance Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single-Arm Vertical Plate Balance Press',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Single arm DB balance press',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Stabilizers', 'Core'],
            ],
            [
                'canonical_name' => 'Cable Fly (Standing)',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated with cuff attachment',
                'notes' => 'Standing cable fly',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Anterior Delts'],
            ],
            [
                'canonical_name' => 'Cable High To Mid Fly',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Cable Fly (Standing)',
                'shoulder_safety_notes' => 'Right tightness at full extension; slightly shorten ROM',
                'notes' => 'High to mid cable fly',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Anterior Delts'],
            ],
            [
                'canonical_name' => 'Pec Fly',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-MCH',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Cable Fly (Standing)',
                'shoulder_safety_notes' => 'Right sensitive with quick movement',
                'notes' => 'Machine pec fly',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Anterior Delts'],
            ],
            [
                'canonical_name' => 'High Cable Tricep Pushdown',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Shoulders roll forward if ROM too high; keep 90-100 degree ROM',
                'notes' => 'High cable tricep pushdown with straight bar',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => ['Forearms'],
            ],
            [
                'canonical_name' => 'Rope Push-Downs',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'High Cable Tricep Pushdown',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Rope attachment pushdown',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => ['Forearms'],
            ],
            [
                'canonical_name' => 'Single-Arm Overhead Cable Extension',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Feels good on anterior capsule; seems to loosen it',
                'notes' => 'Single arm overhead cable extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Single Arm Cable Extensions',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single-Arm Overhead Cable Extension',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'General single arm cable extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Cable Triceps Extension - Quad',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated; significant left-right asymmetry noted',
                'notes' => 'Four-position cable tricep extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Kneeling Single Arm Rope Cable Extension',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single-Arm Overhead Cable Extension',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Kneeling single arm rope extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Standing Single Arm Extension (D-Grip)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single Arm Cable Extensions',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'D-grip single arm cable extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Single-Arm Cable Triceps Extension (Cross-Body)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single Arm Cable Extensions',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cross body cable tricep extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Cable Push-Downs',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Rope Push-Downs',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'General cable pushdown',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Cable: Kneeling 1Arm Overhead Extension',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single-Arm Overhead Cable Extension',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Kneeling overhead cable extension',
                'primary_muscle' => 'Triceps',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Inverted KB Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-KB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Floor press with inverted kettlebell',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Stabilizers'],
            ],
            [
                'canonical_name' => 'Dumbbell Romanian Deadlift',
                'movement_pattern' => 'Hinge',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated; grip limiting factor at heavy weights',
                'notes' => 'Primary hinge movement',
                'primary_muscle' => 'Hamstrings',
                'secondary_muscles' => ['Glutes', 'Lower Back', 'Forearms'],
            ],
            [
                'canonical_name' => 'Bulgarian Split Squat',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Rear foot elevated split squat',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Hamstrings', 'Core'],
            ],
            [
                'canonical_name' => 'Smith Machine Split Squat (rear foot elevated optional)',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-SM',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Bulgarian Split Squat',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Smith machine split squat',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Hamstrings', 'Core'],
            ],
            [
                'canonical_name' => 'Goblet Squat',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Dumbbell or kettlebell goblet squat',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Core', 'Hamstrings'],
            ],
            [
                'canonical_name' => 'Prisoners Squat',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Bodyweight squat with hands behind head',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Core'],
            ],
            [
                'canonical_name' => 'Walking Lunges',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'alternating',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Walking lunge with dumbbells or kettlebell',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Hamstrings', 'Calves'],
            ],
            [
                'canonical_name' => 'Reverse Lunge',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'alternating',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Walking Lunges',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Reverse stepping lunge',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Hamstrings'],
            ],
            [
                'canonical_name' => 'Front-Foot-Elevated Split Squat',
                'movement_pattern' => 'Squat',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Bulgarian Split Squat',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Front foot on plates for increased ROM',
                'primary_muscle' => 'Quads',
                'secondary_muscles' => ['Glutes', 'Hamstrings', 'Core'],
            ],
            [
                'canonical_name' => 'Standing Calf Raise',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-SM',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Smith machine or barbell calf raise',
                'primary_muscle' => 'Calves',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Barbell Standing Calf Raise',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-BB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing Calf Raise',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Barbell calf raise on plates',
                'primary_muscle' => 'Calves',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Seated Calf Raise',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-MCH',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing Calf Raise',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Seated calf raise machine',
                'primary_muscle' => 'Calves',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Calf Extension (Machine)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-MCH',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Standing Calf Raise',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Calf extension on leg press or machine',
                'primary_muscle' => 'Calves',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Glute Extension',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-MCH',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Machine glute extension',
                'primary_muscle' => 'Glutes',
                'secondary_muscles' => ['Hamstrings'],
            ],
            [
                'canonical_name' => 'Dumbbell Lateral Raise',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Slight right anterior capsule awareness at top; better with slight pronation',
                'notes' => 'Dumbbell lateral raise',
                'primary_muscle' => 'Lateral Delts',
                'secondary_muscles' => ['Traps'],
            ],
            [
                'canonical_name' => 'Cable Lateral Raise (using elbow strap setup)',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Dumbbell Lateral Raise',
                'shoulder_safety_notes' => 'Well tolerated with elbow strap',
                'notes' => 'Cable lateral raise using strap at elbow',
                'primary_muscle' => 'Lateral Delts',
                'secondary_muscles' => ['Traps'],
            ],
            [
                'canonical_name' => 'Seated Neutral Grip DB Overhead Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Subtle anterior capsule awareness on descending; tolerance improving',
                'notes' => 'Seated dumbbell overhead press with neutral grip',
                'primary_muscle' => 'Shoulders',
                'secondary_muscles' => ['Triceps', 'Upper Chest'],
            ],
            [
                'canonical_name' => 'Half-Kneeling Single-Arm DB Press',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Half-kneeling single arm overhead press',
                'primary_muscle' => 'Shoulders',
                'secondary_muscles' => ['Triceps', 'Core'],
            ],
            [
                'canonical_name' => 'Pallof Press',
                'movement_pattern' => 'Core',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Core',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated; left side requires more anti-rotation effort',
                'notes' => 'Anti-rotation cable press',
                'primary_muscle' => 'Core',
                'secondary_muscles' => ['Obliques'],
            ],
            [
                'canonical_name' => 'Side Plank',
                'movement_pattern' => 'Core',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'unilateral',
                'exercise_category' => 'Core',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Right shoulder feels looser than left on elbow; palm better tolerated',
                'notes' => 'Isometric lateral core stability',
                'primary_muscle' => 'Obliques',
                'secondary_muscles' => ['Core', 'Shoulders'],
            ],
            [
                'canonical_name' => 'Dead Hang',
                'movement_pattern' => 'Hold',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Hold',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Good scapular reset',
                'notes' => 'Passive hang from pull-up bar',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Lats', 'Shoulders'],
            ],
            [
                'canonical_name' => 'Plate Pinch',
                'movement_pattern' => 'Hold',
                'equipment_code' => 'EQ-PLT',
                'laterality' => 'bilateral',
                'exercise_category' => 'Hold',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Pinch grip hold with weight plates',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Fingers'],
            ],
            [
                'canonical_name' => 'Captains Chair Knee Raises',
                'movement_pattern' => 'Core',
                'equipment_code' => 'EQ-MCH',
                'laterality' => 'bilateral',
                'exercise_category' => 'Core',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Little tightness in right shoulder cap',
                'notes' => 'Hanging knee raise on captain\'s chair',
                'primary_muscle' => 'Core',
                'secondary_muscles' => ['Hip Flexors'],
            ],
            [
                'canonical_name' => 'Hanging Knee Raises',
                'movement_pattern' => 'Core',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Core',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Captains Chair Knee Raises',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Hanging knee raise from pull-up bar',
                'primary_muscle' => 'Core',
                'secondary_muscles' => ['Hip Flexors', 'Forearms'],
            ],
            [
                'canonical_name' => 'Tibia Flex',
                'movement_pattern' => 'Isolation',
                'equipment_code' => 'EQ-PLT',
                'laterality' => 'bilateral',
                'exercise_category' => 'Isolation',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Plate on toe tibialis anterior flexion',
                'primary_muscle' => 'Tibialis Anterior',
                'secondary_muscles' => [],
            ],
            [
                'canonical_name' => 'Rowing',
                'movement_pattern' => 'Cardio',
                'equipment_code' => 'EQ-C2',
                'laterality' => 'bilateral',
                'exercise_category' => 'Cardio',
                'is_time_based' => true,
                'is_distance_based' => true,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Concept2 or similar rowing ergometer',
                'primary_muscle' => 'Full Body',
                'secondary_muscles' => ['Legs', 'Back', 'Arms'],
            ],
            [
                'canonical_name' => 'Treadmill Walking',
                'movement_pattern' => 'Cardio',
                'equipment_code' => 'EQ-TM',
                'laterality' => 'bilateral',
                'exercise_category' => 'Cardio',
                'is_time_based' => true,
                'is_distance_based' => true,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Treadmill walking at various inclines',
                'primary_muscle' => 'Full Body',
                'secondary_muscles' => ['Legs', 'Core'],
            ],
            [
                'canonical_name' => 'Cycling',
                'movement_pattern' => 'Cardio',
                'equipment_code' => 'EQ-BIKE',
                'laterality' => 'bilateral',
                'exercise_category' => 'Cardio',
                'is_time_based' => true,
                'is_distance_based' => true,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Stationary cycling',
                'primary_muscle' => 'Legs',
                'secondary_muscles' => ['Core'],
            ],
            [
                'canonical_name' => 'Endless Rope',
                'movement_pattern' => 'Cardio',
                'equipment_code' => 'EQ-ER',
                'laterality' => 'bilateral',
                'exercise_category' => 'Cardio',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Slight anterior capsule trigger on right at initial reach',
                'notes' => 'Marpo Kinetics or similar endless rope machine',
                'primary_muscle' => 'Forearms',
                'secondary_muscles' => ['Back', 'Shoulders', 'Biceps'],
            ],
            [
                'canonical_name' => 'Push-up',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Little anterior right tightness on lowering',
                'notes' => 'Full push-up from toes',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts', 'Core'],
            ],
            [
                'canonical_name' => 'Push-up On Knees',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Push-up',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Modified push-up from knees',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts', 'Core'],
            ],
            [
                'canonical_name' => 'Incline Push-up',
                'movement_pattern' => 'Push',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Push-up',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Push-up with hands elevated on bar or bench',
                'primary_muscle' => 'Chest',
                'secondary_muscles' => ['Triceps', 'Anterior Delts', 'Core'],
            ],
            [
                'canonical_name' => 'Scap Push Ups',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Scapular protraction/retraction from push-up position',
                'primary_muscle' => 'Serratus Anterior',
                'secondary_muscles' => ['Shoulders'],
            ],
            [
                'canonical_name' => 'Band Pull Aparts',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BAND',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Band pull apart for shoulder warmup',
                'primary_muscle' => 'Rear Delts',
                'secondary_muscles' => ['Rhomboids', 'Traps'],
            ],
            [
                'canonical_name' => 'Band External Rotations',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BAND',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Banded external rotation warmup',
                'primary_muscle' => 'External Rotators',
                'secondary_muscles' => ['Rotator Cuff'],
            ],
            [
                'canonical_name' => 'Serratus Wall Slides (banded)',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BAND',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Wall slide with band around wrists',
                'primary_muscle' => 'Serratus Anterior',
                'secondary_muscles' => ['Shoulders', 'Traps'],
            ],
            [
                'canonical_name' => 'Cat-Camel',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Spinal flexion/extension mobilization',
                'primary_muscle' => 'Spine',
                'secondary_muscles' => ['Core'],
            ],
            [
                'canonical_name' => 'Cable External Rotation',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Band External Rotations',
                'shoulder_safety_notes' => 'Left has less ROM than right',
                'notes' => 'Cable external rotation',
                'primary_muscle' => 'External Rotators',
                'secondary_muscles' => ['Rotator Cuff'],
            ],
            [
                'canonical_name' => 'Inverted KB Hold',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-KB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Rehab',
                'is_time_based' => true,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Inverted kettlebell hold for shoulder stability',
                'primary_muscle' => 'Shoulders',
                'secondary_muscles' => ['Forearms', 'Stabilizers'],
            ],
            [
                'canonical_name' => 'Vertical DB Scap extension',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-DB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Rehab',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Vertical dumbbell or plate scapular extension',
                'primary_muscle' => 'Serratus Anterior',
                'secondary_muscles' => ['Shoulders'],
            ],
            [
                'canonical_name' => 'Hip Hinge',
                'movement_pattern' => 'Mobility',
                'equipment_code' => 'EQ-BW',
                'laterality' => 'bilateral',
                'exercise_category' => 'Warmup',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Bodyweight hip hinge pattern warmup',
                'primary_muscle' => 'Hamstrings',
                'secondary_muscles' => ['Glutes', 'Lower Back'],
            ],
            [
                'canonical_name' => 'Cable Pull-Through',
                'movement_pattern' => 'Hinge',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'bilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => null,
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Cable pull-through for hip extension',
                'primary_muscle' => 'Glutes',
                'secondary_muscles' => ['Hamstrings', 'Lower Back'],
            ],
            [
                'canonical_name' => 'Half-Kneeling Single-Arm Cable Pulldown',
                'movement_pattern' => 'Pull',
                'equipment_code' => 'EQ-CAB',
                'laterality' => 'unilateral',
                'exercise_category' => 'Compound',
                'is_time_based' => false,
                'is_distance_based' => false,
                'preferred_replacements' => 'Single-Arm Neutral Grip Cable Pulldown',
                'shoulder_safety_notes' => 'Well tolerated',
                'notes' => 'Half-kneeling single arm cable pulldown',
                'primary_muscle' => 'Lats',
                'secondary_muscles' => ['Biceps', 'Forearms'],
            ],
        ];

        foreach ($rows as $row) {
            $equipment = $row['equipment_code'] ? Equipment::where('external_code', $row['equipment_code'])->first() : null;

            $exercise = Exercise::updateOrCreate(
                ['canonical_name' => $row['canonical_name']],
                [
                    'movement_pattern' => $row['movement_pattern'],
                    'equipment_id' => $equipment?->id,
                    'laterality' => $row['laterality'],
                    'exercise_category' => $row['exercise_category'],
                    'is_time_based' => $row['is_time_based'],
                    'is_distance_based' => $row['is_distance_based'],
                    'preferred_replacements' => $row['preferred_replacements'],
                    'shoulder_safety_notes' => $row['shoulder_safety_notes'],
                    'notes' => $row['notes'],
                ]
            );

            $structureIds = [];
            if ($primary = BodyStructure::where('name', $row['primary_muscle'])->first()) {
                $structureIds[$primary->id] = ['role' => 'primary'];
            }
            foreach ($row['secondary_muscles'] as $name) {
                if ($structure = BodyStructure::where('name', $name)->first()) {
                    $structureIds[$structure->id] = ['role' => 'secondary'];
                }
            }
            $exercise->bodyStructures()->sync($structureIds);
        }
    }
}
