@extends('layouts.ecosystem')
@section('title', 'Bulldog gear preview')
@section('content')
<section class="hero"><div class="eyebrow">The Bulldog collection / Coming soon</div><h1>Wear the work.</h1><p>From the dugout to the weight room. A first look at the pieces we’re exploring for the Bulldog community.</p><span class="badge" style="color:var(--ink)">DESIGN CONCEPTS · NOT FOR SALE</span></section>
<div class="grid three"><article class="panel"><div class="gear"><svg viewBox="0 0 180 180" role="img" aria-label="Navy Bulldog training shirt concept"><path d="M55 25 20 48 35 82 53 70 53 155 127 155 127 70 145 82 160 48 125 25 110 35 70 35Z" fill="#0b2b45"/><path d="M70 35Q90 65 110 35" fill="none" stroke="#b5ebce" stroke-width="4"/><image href="{{ asset('coach.png') }}" x="72" y="64" width="36" height="36"/></svg></div><h2>Everyday training tee</h2><p>A quiet mark. A strong identity. Navy with the Bulldog emblem at the chest.</p><span class="quiet">Concept illustration · Materials and sizing to be confirmed</span></article>
<article class="panel"><div class="gear"><svg viewBox="0 0 180 180" role="img" aria-label="Green Bulldog cap concept"><path d="M30 110Q25 35 90 35T150 110Z" fill="#007a43"/><path d="M30 110Q105 95 166 131Q111 156 30 124Z" fill="#0b2b45"/><image href="{{ asset('coach.png') }}" x="70" y="60" width="40" height="40"/></svg></div><h2>Dugout cap</h2><p>A little team pride, wherever the day takes you. Deep green with a navy brim.</p><span class="quiet">Concept illustration · Fit and construction to be confirmed</span></article>
<article class="panel"><div class="gear"><svg viewBox="0 0 180 180" role="img" aria-label="Bulldog water bottle concept"><rect x="72" y="20" width="36" height="23" rx="5" fill="#007a43"/><rect x="58" y="42" width="64" height="118" rx="18" fill="#0b2b45"/><image href="{{ asset('coach.png') }}" x="68" y="77" width="44" height="44"/></svg></div><h2>Training bottle</h2><p>One familiar companion for the field, the gym, and the space between.</p><span class="quiet">Concept illustration · Capacity and materials to be confirmed</span></article></div>
<section class="panel" style="margin-top:24px"><h2>Built with the community.</h2><p>This is a preview, not an order page. Final products, availability, and pricing will be announced when the collection is ready.</p><a href="{{ route('dashboard') }}">Back to your home base →</a></section>
@endsection
