@extends('layouts.ecosystem')
@section('title', 'Nutrition preview')
@section('content')
<section class="hero"><div class="eyebrow">Bulldog Nutrition / Coming soon</div><h1>Fuel the work.<br>Keep it practical.</h1><p>A first look at food-first education and recipes for adults who train. Explore now; interactive tools are still on the way.</p><span class="badge" style="color:var(--ink)">EDUCATION PREVIEW · NO TRACKING</span></section>
<div class="grid three"><article class="panel"><div class="eyebrow">01 / Protein</div><h2>Food first. Powder if useful.</h2><p>Protein supports muscle repair and adaptation. Foods such as yogurt, beans, tofu, fish, and poultry can contribute throughout the day.</p><p class="quiet">A supplement can be convenient, but it is not necessary when food already meets your needs. Check ingredients and allergens.</p></article>
<article class="panel"><div class="eyebrow">02 / Creatine</div><h2>Useful for some training.</h2><p>Creatine can help repeated bursts of intense activity, such as lifting. Its benefits are less clear for endurance performance.</p><p class="quiet">Weight gain from water retention can occur. This preview offers no personal dosing plan; discuss suitability with a qualified professional.</p></article>
<article class="panel"><div class="eyebrow">03 / Caffeine</div><h2>Energy has a trade-off.</h2><p>Caffeine may improve some exercise performance, but responses vary. It can disrupt sleep and cause anxiety or a rapid heartbeat.</p><p class="quiet">More is not always better. Count all sources, including pre-workouts, coffee, and energy drinks.</p></article></div>
<p class="quiet" style="margin:20px 0 36px">Source: <a href="https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/" target="_blank" rel="noopener">NIH Office of Dietary Supplements: Exercise and athletic performance</a>. Educational information for adults, not an individualized nutrition plan.</p>
<h2>A few ideas for your next training day.</h2><div class="grid three">
<article class="panel recipe"><span class="eyebrow">5 minutes / No cook</span><h3>Yogurt recovery bowl</h3><p>Combine ¾ cup plain Greek yogurt, ½ cup oats, a handful of berries, and a spoon of pumpkin seeds. Loosen with milk or water and finish with cinnamon.</p><p class="quiet">Protein ingredient: Greek yogurt. Contains dairy; check oats for gluten cross-contact when relevant.</p></article>
<article class="panel recipe"><span class="eyebrow">15 minutes / One pan</span><h3>Tofu and bean skillet</h3><p>Crumble 200 g firm tofu into a hot pan with olive oil. Add ½ cup drained black beans, diced peppers, cumin, and smoked paprika. Cook until hot; serve over rice with lime.</p><p class="quiet">Protein ingredients: tofu and beans. Contains soy.</p></article>
<article class="panel recipe"><span class="eyebrow">10 minutes / Prep friendly</span><h3>Chicken chickpea wrap</h3><p>Toss cooked chicken, drained chickpeas, chopped cucumber, and plain yogurt with lemon. Spoon into a wholegrain wrap. Keep chilled until ready to eat.</p><p class="quiet">Protein ingredients: chicken, chickpeas, yogurt. Contains dairy and wheat unless substituted.</p></article></div>
@endsection
