@extends('layouts.ecosystem')
@section('title', $team->name)
@section('content')
<section class="hero"><div class="eyebrow">{{ $team->sport->name }} / {{ $team->season_label ?: 'Your season' }}</div><h1>{{ $team->name }}</h1><p>{{ $team->age_group }} · {{ $team->memberships->count() }} roster slots</p>@can('manageRoster', $team)<a class="action" href="{{ route('games.create') }}">Schedule a game →</a>@endcan</section>
<section class="panel"><h2>Your roster</h2><div class="table-wrap"><table><thead><tr><th>Player</th><th>Jersey</th><th>Identity</th></tr></thead><tbody>@forelse($team->memberships as $member)<tr><td>@if($member->playerIdentity)@can('view', $member->playerIdentity)<a href="{{ route('players.show', $member->playerIdentity) }}">{{ $member->playerIdentity->display_name }}</a>@else<span>Private player</span>@endcan @endif</td><td>{{ $member->jersey_number ?: '—' }}</td><td>Private</td></tr>@empty<tr><td colspan="3">No players yet. Add your first roster slot below.</td></tr>@endforelse</tbody></table></div></section>
@can('manageRoster', $team)<div class="grid"><section class="panel"><h2>Add a new player</h2><form class="stack" method="post" action="{{ route('teams.roster', $team) }}">@csrf<label for="display_name">Display name</label><input id="display_name" name="display_name" required maxlength="100"><label for="birth_year">Birth year (optional)</label><input id="birth_year" name="birth_year" type="number" min="1900" max="{{ date('Y') }}"><label for="jersey_number">Jersey number</label><input id="jersey_number" name="jersey_number" maxlength="10"><button>Add private player</button></form></section>
<section class="panel"><h2>Link an existing player</h2><p class="quiet">Search identities you already manage. There is no public player directory.</p><form method="get"><label for="search">Player name</label><input id="search" name="search" value="{{ request('search') }}"><button class="secondary" style="margin-top:12px">Search</button></form>@foreach($players as $player)<form method="post" action="{{ route('teams.roster', $team) }}" class="actions" style="margin-top:16px">@csrf<input type="hidden" name="player_identity_id" value="{{ $player->id }}"><span>{{ $player->display_name }}</span><button class="secondary">Link player</button></form>@endforeach</section></div>@endcan
@can('assignRoles', $team)<section class="panel" style="margin-top:22px"><h2>Guardian relationships</h2><p>Invite an adult using their account email. They accept in Guardian invitations; you then confirm the relationship.</p><form class="stack" method="post" action="{{ route('guardians.invite', $team) }}">@csrf<label for="child">Youth player</label><select id="child" name="player_identity_id" required>@foreach($team->memberships as $member)@if($member->playerIdentity && !$member->playerIdentity->user_id)<option value="{{ $member->player_identity_id }}">{{ $member->playerIdentity->display_name }}</option>@endif @endforeach</select><label for="email">Guardian email</label><input id="email" name="email" type="email" required><button>Create invitation</button></form>
@foreach($relationships as $relationship)<div class="actions" style="margin-top:20px"><span>{{ $relationship->playerIdentity->display_name }} · {{ $relationship->invited_email }} · {{ $relationship->verification_status }}</span>@if($relationship->verification_status === 'accepted')<form method="post" action="{{ route('guardians.confirm', $relationship) }}">@csrf<button>Confirm relationship</button></form>@endif @if($relationship->verification_status !== 'revoked')<form method="post" action="{{ route('guardians.revoke', $relationship) }}">@csrf<button class="secondary">Revoke</button></form>@endif</div>@endforeach</section>@endcan
@endsection
