@extends('layouts.ecosystem')
@section('title', 'Live scorebook')
@section('content')
<div class="eyebrow">Statbook / {{ $game->is_demo ? 'Guided practice · Fictional players' : 'Live scorebook' }}</div>
<div class="panel scoreboard"><div class="score-team"><h3>{{ $game->awayTeam->name }}</h3><div class="score">{{ $currentState->score_away }}</div></div><div><span class="badge">{{ $game->status === 'finalized' ? 'FINAL' : strtoupper($currentState->half_inning).' '.$currentState->inning_number }}</span><p style="margin:14px 0 0">{{ $currentState->outs }} outs · {{ $currentState->balls }}–{{ $currentState->strikes }}</p><span class="quiet">Bases: {{ $currentState->base_state }}</span></div><div class="score-team"><h3>{{ $game->homeTeam->name }}</h3><div class="score">{{ $currentState->score_home }}</div></div></div>
@if($game->is_demo)<section class="panel" x-data="{ step: 1 }"><div class="coach"><img src="{{ asset('coach.png') }}" alt="Coach"><div><strong>Learn the scorebook with Coach</strong><p class="quiet">Practice only: no season totals, career records, or XP.</p></div></div><p x-show="step === 1">1. Choose the batter and pitcher. The away team bats in the top half; the home team bats in the bottom half.</p><p x-show="step === 2" x-cloak>2. Record the result of the plate appearance below. Try a single, a walk, and a home run. Watch the bases and score change.</p><p x-show="step === 3" x-cloak>3. Record three outs to switch sides. Continue through the innings, then finalize to inspect your box score.</p><button type="button" class="secondary" @click="step = step === 3 ? 1 : step + 1">Next tip</button></section>@endif
@if($game->status !== 'finalized')
<form class="panel" method="post" action="{{ route('games.score.store', $game) }}">@csrf<input type="hidden" name="event_family" value="plate_appearance"><h2>Record a plate appearance</h2><p class="quiet">Enter the completed result. Hits advance runners by the hit distance. This beta scorebook supports hits, walks, strikeouts, and other outs.</p>
<div class="grid"><div><label for="batter">Batter</label><select id="batter" name="players[0][player_identity_id]" required>@foreach($game->gameRosterEntries->where('team_id', $currentState->half_inning === 'top' ? $game->away_team_id : $game->home_team_id)->where('eligible_to_play', true) as $entry)<option value="{{ $entry->player_identity_id }}">{{ $entry->playerIdentity->display_name }}</option>@endforeach</select><input type="hidden" name="players[0][role]" value="batter"></div><div><label for="pitcher">Pitcher</label><select id="pitcher" name="players[1][player_identity_id]" required>@foreach($game->gameRosterEntries->where('team_id', $currentState->half_inning === 'top' ? $game->home_team_id : $game->away_team_id)->where('eligible_to_play', true) as $entry)<option value="{{ $entry->player_identity_id }}">{{ $entry->playerIdentity->display_name }}</option>@endforeach</select><input type="hidden" name="players[1][role]" value="pitcher"></div></div>
<div class="scoring-buttons">@foreach(['single'=>'Single','double'=>'Double','triple'=>'Triple','home_run'=>'Home run','walk'=>'Walk','strikeout'=>'Strikeout','out'=>'Other out'] as $value=>$label)<button name="event_type" value="{{ $value }}">{{ $label }}</button>@endforeach</div></form>
<form method="post" action="{{ route('games.finalize', $game) }}" class="panel" x-data="{ confirm: false }"><h3>Finish this {{ $game->is_demo ? 'practice' : 'game' }}</h3><p>Finalize when both sides have finished. Further event entry will be locked.</p>@csrf<label><input type="checkbox" x-model="confirm"> The game is complete.</label><button :disabled="!confirm">Finalize and view box score</button></form>
@endif
<section class="panel"><h2>Box score</h2><div class="table-wrap"><table><thead><tr><th>Player / team</th>@foreach(['AB','H','2B','3B','HR','BB','SO','SO_pitching','IP_outs'] as $stat)<th>{{ $stat }}</th>@endforeach</tr></thead><tbody>@forelse($boxScore as $stats)<tr><td>{{ $stats->first()->playerIdentity->display_name }}<br><small>{{ $stats->first()->team->name }}</small></td>@foreach(['AB','H','2B','3B','HR','BB','SO','SO_pitching','IP_outs'] as $stat)<td>{{ (int) ($stats->firstWhere('stat_key', $stat)?->stat_value ?? 0) }}</td>@endforeach</tr>@empty<tr><td colspan="10">Record the first play to build your box score.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Recent plays</h2>@forelse($events as $event)<p><span class="badge">{{ $event->half_inning }} {{ $event->inning_number }}</span> {{ str_replace('_',' ',$event->event_type) }} · {{ $event->score_away_after }}–{{ $event->score_home_after }}</p>@empty<p>No plays yet.</p>@endforelse</section>
@endsection
